Vendor version 1.0.7

diff --git a/mpich2/src/mpe2/src/logging/configure b/mpich2/src/mpe2/src/logging/configure
--- a/mpich2/src/mpe2/src/logging/configure
+++ b/mpich2/src/mpe2/src/logging/configure
@@ -308,7 +308,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS top_srcdir_abs VPATH MAKE MKDIR CPRP RM MV includebuild_dir libbuild_dir binbuild_dir etcbuild_dir CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT AR RANLIB ac_ct_RANLIB CPP EGREP mpe_c99_stdint_inc mpe_c99_pridxx_inc mpe_int8_t mpe_int16_t mpe_int32_t mpe_int64_t mpe_int8_fmt mpe_int16_fmt mpe_int32_fmt mpe_int64_fmt ZMPI_AINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os PTHREAD_IN_MPI_DEF THREAD_LOG_LIBS MPE_BUILD_FORTRAN2C CLINKER MPI_CC MPI_INC MPI_LIBS PROF_LIBNAME LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS top_srcdir_abs VPATH MAKE MKDIR CPRP RM MV includebuild_dir libbuild_dir binbuild_dir etcbuild_dir CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT AR RANLIB ac_ct_RANLIB CPP EGREP mpe_c99_stdint_inc mpe_c99_pridxx_inc mpe_int8_t mpe_int16_t mpe_int32_t mpe_int64_t mpe_int8_fmt mpe_int16_fmt mpe_int32_fmt mpe_int64_fmt ZMPI_AINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os PTHREAD_IN_MPI_DEF THREAD_LOG_LIBS MPE_BUILD_FORTRAN2C CLINKER MPI_CC MPI_CFLAGS MPI_LIBS PROF_LIBNAME LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1368,7 +1368,7 @@ CC=${CC:-cc}
 CLINKER=${CLINKER:-$CC}
 CFLAGS=${MPE_CFLAGS}
 MPI_CC=${MPI_CC:-${CC}}
-MPI_INC=${MPI_INC}
+MPI_CFLAGS=${MPI_CFLAGS}
 MPI_LIBS=${MPI_LIBS}
 
 MPE_LIBNAME=${MPE_LIBNAME:-mpe}
@@ -3484,7 +3484,9 @@ done
 
 
 
-for ac_header in stdio.h stdlib.h string.h unistd.h sys/time.h sys/types.h sys/bitypes.h
+
+
+for ac_header in stdio.h stdlib.h string.h unistd.h sys/time.h sys/types.h sys/bitypes.h sys/stat.h fcntl.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -7929,46 +7931,36 @@ fi
 rm -f conftest*
 fi
 
-echo "$as_me:$LINENO: checking whether _LARGEFILE64_SOURCE is needed " >&5
-echo $ECHO_N "checking whether _LARGEFILE64_SOURCE is needed ... $ECHO_C" >&6
-if test "$ac_cv_sys_file_offset_bits" != no \
-     -o "$ac_cv_sys_large_files" != no ; then
-
-cat >>confdefs.h <<\_ACEOF
-#define _LARGEFILE64_SOURCE 1
-_ACEOF
-
-    echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-else
-    echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-
-for ac_header in fcntl.h
-do
-as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
-if eval "test \"\${$as_ac_Header+set}\" = set"; then
-  echo "$as_me:$LINENO: checking for $ac_header" >&5
-echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
-if eval "test \"\${$as_ac_Header+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
-else
-  # Is the header compilable?
-echo "$as_me:$LINENO: checking $ac_header usability" >&5
-echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
+if test "$enable_largefile" != no ; then
+    echo "$as_me:$LINENO: checking for O_LARGEFILE for open() " >&5
+echo $ECHO_N "checking for O_LARGEFILE for open() ... $ECHO_C" >&6
+    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-$ac_includes_default
-#include <$ac_header>
+
+#if defined( HAVE_SYS_TYPES_H )
+#include <sys/types.h>
+#endif
+#if defined( HAVE_SYS_STAT_H )
+#include <sys/stat.h>
+#endif
+#if defined( HAVE_FCNTL_H )
+#include <fcntl.h>
+#endif
+
+int
+main ()
+{
+
+    int fd;
+    fd = open( "tmpfile", O_CREAT | O_LARGEFILE, 0644 );
+
+  ;
+  return 0;
+}
 _ACEOF
 rm -f conftest.$ac_objext
 if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
@@ -7991,120 +7983,118 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_header_compiler=yes
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_O_LARGEFILE 1
+_ACEOF
+
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_header_compiler=no
+
+        cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#define _LARGEFILE64_SOURCE
+#if defined( HAVE_SYS_TYPES_H )
+#include <sys/types.h>
+#endif
+#if defined( HAVE_SYS_STAT_H )
+#include <sys/stat.h>
+#endif
+#if defined( HAVE_FCNTL_H )
+#include <fcntl.h>
+#endif
+
+int
+main ()
+{
+
+    int fd;
+    fd = open( "tmpfile", O_CREAT | O_LARGEFILE, 0644 );
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_O_LARGEFILE 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define _LARGEFILE64_SOURCE 1
+_ACEOF
+
+            echo "$as_me:$LINENO: result: needs _LARGEFILE64_SOURCE " >&5
+echo "${ECHO_T}needs _LARGEFILE64_SOURCE " >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+            echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
-echo "${ECHO_T}$ac_header_compiler" >&6
 
-# Is the header present?
-echo "$as_me:$LINENO: checking $ac_header presence" >&5
-echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+
+echo "$as_me:$LINENO: checking for O_BINARY for open() " >&5
+echo $ECHO_N "checking for O_BINARY for open() ... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <$ac_header>
-_ACEOF
-if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
-  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } >/dev/null; then
-  if test -s conftest.err; then
-    ac_cpp_err=$ac_c_preproc_warn_flag
-    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
-  else
-    ac_cpp_err=
-  fi
-else
-  ac_cpp_err=yes
-fi
-if test -z "$ac_cpp_err"; then
-  ac_header_preproc=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
 
-  ac_header_preproc=no
-fi
-rm -f conftest.err conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
-echo "${ECHO_T}$ac_header_preproc" >&6
-
-# So?  What about this header?
-case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
-  yes:no: )
-    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
-    ac_header_preproc=yes
-    ;;
-  no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
-echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
-    (
-      cat <<\_ASBOX
-## ------------------------------------------ ##
-## Report this to the AC_PACKAGE_NAME lists.  ##
-## ------------------------------------------ ##
-_ASBOX
-    ) |
-      sed "s/^/$as_me: WARNING:     /" >&2
-    ;;
-esac
-echo "$as_me:$LINENO: checking for $ac_header" >&5
-echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
-if eval "test \"\${$as_ac_Header+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  eval "$as_ac_Header=\$ac_header_preproc"
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
-
-fi
-if test `eval echo '${'$as_ac_Header'}'` = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
-_ACEOF
- echo "$as_me:$LINENO: checking for O_BINARY for open() " >&5
-echo $ECHO_N "checking for O_BINARY for open() ... $ECHO_C" >&6
-    cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-        #include <fcntl.h>
+#if defined( HAVE_FCNTL_H )
+#include <fcntl.h>
+#endif
 
 int
 main ()
 {
 
-        open( "tmpfile", O_CREAT | O_BINARY );
+    int fd;
+    fd = open( "tmpfile", O_CREAT | O_BINARY, 0644 );
 
   ;
   return 0;
@@ -8132,34 +8122,32 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
 
+
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_O_BINARY 1
 _ACEOF
 
-        echo "$as_me:$LINENO: result: yes" >&5
+    echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
+
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-echo "$as_me:$LINENO: result: no" >&5
+
+    echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 
-fi
-
-done
-
-
 if test "$MPI_IMPL" != "MPICH" -a "$MPI_IMPL" != "MPICH2" ; then
     echo "$as_me:$LINENO: checking for PMPI_Comm_create_keyval() " >&5
 echo $ECHO_N "checking for PMPI_Comm_create_keyval() ... $ECHO_C" >&6
 
     pac_MPI_CC="$MPI_CC"
-    pac_MPI_CFLAGS="$CFLAGS $MPI_INC"
+    pac_MPI_CFLAGS="$MPI_CFLAGS"
     pac_MPI_LIBS="$MPI_LIBS"
 
 
@@ -8281,7 +8269,7 @@ if test "$MPI_IMPL" != "MPICH" -a "$MPI_IMPL" != "MPICH2" ; then
 echo $ECHO_N "checking for PMPI_Comm_free_keyval() ... $ECHO_C" >&6
 
     pac_MPI_CC="$MPI_CC"
-    pac_MPI_CFLAGS="$CFLAGS $MPI_INC"
+    pac_MPI_CFLAGS="$MPI_CFLAGS"
     pac_MPI_LIBS="$MPI_LIBS"
 
 
@@ -8401,7 +8389,7 @@ if test "$MPI_IMPL" != "MPICH" -a "$MPI_IMPL" != "MPICH2" ; then
 echo $ECHO_N "checking for PMPI_Comm_set_attr() ... $ECHO_C" >&6
 
     pac_MPI_CC="$MPI_CC"
-    pac_MPI_CFLAGS="$CFLAGS $MPI_INC"
+    pac_MPI_CFLAGS="$MPI_CFLAGS"
     pac_MPI_LIBS="$MPI_LIBS"
 
 
@@ -8522,7 +8510,7 @@ if test "$MPI_IMPL" != "MPICH" -a "$MPI_IMPL" != "MPICH2" ; then
 echo $ECHO_N "checking for PMPI_Comm_get_attr() ... $ECHO_C" >&6
 
     pac_MPI_CC="$MPI_CC"
-    pac_MPI_CFLAGS="$CFLAGS $MPI_INC"
+    pac_MPI_CFLAGS="$MPI_CFLAGS"
     pac_MPI_LIBS="$MPI_LIBS"
 
 
@@ -8876,7 +8864,7 @@ if test "$MPI_IMPL" != "MPICH" -a "$MPI_IMPL" != "MPICH2" ; then
 echo $ECHO_N "checking for pthread_mutex_lock/unlock in MPI ... $ECHO_C" >&6
 
     pac_MPI_CC="$MPI_CC"
-    pac_MPI_CFLAGS="$CFLAGS $MPI_INC"
+    pac_MPI_CFLAGS="$MPI_CFLAGS"
     pac_MPI_LIBS="$MPI_LIBS"
 
 
@@ -8982,7 +8970,7 @@ echo "${ECHO_T}yes" >&6
         else
 
     pac_MPI_CC="$MPI_CC"
-    pac_MPI_CFLAGS="$CFLAGS $MPI_INC"
+    pac_MPI_CFLAGS="$MPI_CFLAGS"
     pac_MPI_LIBS="$MPI_LIBS -lpthread"
 
 
@@ -9727,7 +9715,7 @@ s,@THREAD_LOG_LIBS@,$THREAD_LOG_LIBS,;t t
 s,@MPE_BUILD_FORTRAN2C@,$MPE_BUILD_FORTRAN2C,;t t
 s,@CLINKER@,$CLINKER,;t t
 s,@MPI_CC@,$MPI_CC,;t t
-s,@MPI_INC@,$MPI_INC,;t t
+s,@MPI_CFLAGS@,$MPI_CFLAGS,;t t
 s,@MPI_LIBS@,$MPI_LIBS,;t t
 s,@PROF_LIBNAME@,$PROF_LIBNAME,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
diff --git a/mpich2/src/mpe2/src/misc/configure b/mpich2/src/mpe2/src/misc/configure
--- a/mpich2/src/mpe2/src/misc/configure
+++ b/mpich2/src/mpe2/src/misc/configure
@@ -308,7 +308,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS top_srcdir_abs VPATH MAKE MKDIR CPRP RM MV build build_cpu build_vendor build_os host host_cpu host_vendor host_os includebuild_dir libbuild_dir binbuild_dir CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT AR RANLIB ac_ct_RANLIB CPP DBX_NAME GDB_NAME EGREP MPI_IMPL MPE_BUILD_FORTRAN2C MPEDBG CLINKER MPI_CC MPI_INC MPI_LIBS PROF_LIBNAME LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS top_srcdir_abs VPATH MAKE MKDIR CPRP RM MV build build_cpu build_vendor build_os host host_cpu host_vendor host_os includebuild_dir libbuild_dir binbuild_dir CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT AR RANLIB ac_ct_RANLIB CPP DBX_NAME GDB_NAME EGREP MPI_IMPL MPE_BUILD_FORTRAN2C MPEDBG CLINKER MPI_CC MPI_CFLAGS MPI_LIBS PROF_LIBNAME LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1369,7 +1369,7 @@ CC=${CC:-cc}
 CLINKER=${CLINKER:-$CC}
 CFLAGS=${MPE_CFLAGS}
 MPI_CC=${MPI_CC:-$CC}
-MPI_INC=${MPI_INC}
+MPI_CFLAGS=${MPI_CFLAGS}
 MPI_LIBS=${MPI_LIBS}
 
 MPE_LIBNAME=${MPE_LIBNAME:-mpe}
@@ -1615,27 +1615,33 @@ host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 case "$host" in
    *alpha*)
         CFLAGS="$CFLAGS -DDBX_IS_OSF"
+        MPI_CFLAGS="$MPI_CFLAGS -DDBX_IS_OSF"
         host=alpha
         ;;
    *rs6000*)
         host=rs6000
         CFLAGS="$CFLAGS -DMPI_rs6000"
+        MPI_CFLAGS="$MPI_CFLAGS -DMPI_rs6000"
         ;;
    *solaris*)
         host=solaris
         CFLAGS="$CFLAGS -DMPI_solaris"
+        MPI_CFLAGS="$MPI_CFLAGS -DMPI_solaris"
         ;;
     *linux*)
         host=linux
         CFLAGS="$CFLAGS -DMPI_LINUX"
+        MPI_CFLAGS="$MPI_CFLAGS -DMPI_LINUX"
         ;;
     *sun4*)
         host=sun4
         CFLAGS="$CFLAGS -DMPI_sun4"
+        MPI_CFLAGS="$MPI_CFLAGS -DMPI_sun4"
         ;;
     mips-sgi-irix*)
         host=irix
         CFLAGS="$CFLAGS -DMPI_IRIX"
+        MPI_CFLAGS="$MPI_CFLAGS -DMPI_IRIX"
         ;;
 esac
 
@@ -3704,7 +3710,8 @@ done
 
 
 
-for ac_header in unistd.h stdlib.h string.h netdb.h sys/systeminfo.h
+
+for ac_header in unistd.h stdlib.h string.h netdb.h sys/systeminfo.h sys/types.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -3906,6 +3913,173 @@ if test "$has_sighandler_t" = "yes" ; then
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_SIGHANDLER_T 1
 _ACEOF
+
+fi
+
+
+for ac_func in kill
+do
+as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_func" >&5
+echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
+if eval "test \"\${$as_ac_var+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define $ac_func to an innocuous variant, in case <limits.h> declares $ac_func.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define $ac_func innocuous_$ac_func
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef $ac_func
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+{
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $ac_func ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+choke me
+#else
+char (*f) () = $ac_func;
+#endif
+#ifdef __cplusplus
+}
+#endif
+
+int
+main ()
+{
+return f != $ac_func;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_var=no"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+done
+
+if test "$ac_cv_func_kill" = "yes" ; then
+
+echo "$as_me:$LINENO: checking whether kill needs a declaration" >&5
+echo $ECHO_N "checking whether kill needs a declaration... $ECHO_C" >&6
+if test "${pac_cv_func_decl_kill+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <signal.h>
+int
+main ()
+{
+int a=kill(1.0,27,1.0,"foo");
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  pac_cv_func_decl_kill=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+pac_cv_func_decl_kill=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $pac_cv_func_decl_kill" >&5
+echo "${ECHO_T}$pac_cv_func_decl_kill" >&6
+if test "$pac_cv_func_decl_kill" = "yes" ; then
+
+cat >>confdefs.h <<_ACEOF
+#define NEEDS_KILL_DECL 1
+_ACEOF
+
+
+fi
 
 fi
 
@@ -4517,7 +4691,7 @@ s,@MPE_BUILD_FORTRAN2C@,$MPE_BUILD_FORTRAN2C,;t t
 s,@MPEDBG@,$MPEDBG,;t t
 s,@CLINKER@,$CLINKER,;t t
 s,@MPI_CC@,$MPI_CC,;t t
-s,@MPI_INC@,$MPI_INC,;t t
+s,@MPI_CFLAGS@,$MPI_CFLAGS,;t t
 s,@MPI_LIBS@,$MPI_LIBS,;t t
 s,@PROF_LIBNAME@,$PROF_LIBNAME,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
