Vendor version 1.0.8rc1

diff --git a/mpich2/src/env/mpicxx.in b/mpich2/src/env/mpicxx.in
--- a/mpich2/src/env/mpicxx.in
+++ b/mpich2/src/env/mpicxx.in
@@ -140,7 +140,10 @@ for arg in "$@" ; do
     -v)
     # Pass this argument to the compiler as well.
     echo "mpicxx for $MPIVERSION"
-    linking=no
+    # if there is only 1 argument, it must be -v.
+    if [ "$#" -eq "1" ] ; then
+        linking=no
+    fi
     ;;
     -profile=*)
     # Pass the name of a profiling configuration.  As
@@ -158,8 +161,18 @@ for arg in "$@" ; do
     addarg=no
     # Loading the profConf file is handled below
     ;;
-	# -help
     -help)
+    NC=`echo "$CXX" | sed 's%\/% %g' | awk '{print $NF}' -`
+    if [ -f "$sysconfdir/mpixxx_opts.conf" ] ; then
+        . $sysconfdir/mpixxx_opts.conf
+        echo "    -cxx=xxx      - Reset the native compiler to xxx."
+    else
+        if [ -f "./mpixxx_opts.conf" ] ; then
+            . ./mpixxx_opts.conf
+            echo "    -cxx=xxx      - Reset the native compiler to xxx."
+        fi
+    fi
+    exit 0
     ;;
         # -----------------------------------------------------------------
 	# Other arguments.  We are careful to handle arguments with 
@@ -180,6 +193,12 @@ for arg in "$@" ; do
         allargs="$allargs $qarg"
     fi
 done
+
+if [ $# -eq 0 ] ; then
+    echo "Error: Command line argument is needed!"
+    "$0" -help
+    exit 1
+fi
 
 # -----------------------------------------------------------------------
 # Derived variables.  These are assembled from variables set from the
diff --git a/mpich2/src/mpi/errhan/Makefile.in b/mpich2/src/mpi/errhan/Makefile.in
--- a/mpich2/src/mpi/errhan/Makefile.in
+++ b/mpich2/src/mpi/errhan/Makefile.in
@@ -6,6 +6,7 @@
 all: all-redirect
 
 SHELL           = @SHELL@
+VERBOSE         = 1
 AR              = @AR@
 RANLIB          = @RANLIB@
 master_top_srcdir  = @master_top_srcdir@
@@ -47,14 +48,30 @@ INCLUDES = -I../../include -I${top_srcdir}/src/include
 .SUFFIXES:
 .SUFFIXES: .o .lo .c .man .html .latex .txt 
 .c.o:
-	$(C_COMPILE) -c $<
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              $<" ; \
+	else \
+	  echo $(C_COMPILE) -c $< ; \
+	fi
+	@$(C_COMPILE) -c $<
 .c.lo:
-	$(C_COMPILE_SHL) -c $< -o _s$*.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              $<" ; \
+	else \
+	  echo $(C_COMPILE_SHL) -c $< -o _s$*.o ; \
+	echo mv -f _s$*.o $*.lo ; \
+	fi
+	@$(C_COMPILE_SHL) -c $< -o _s$*.o
 	@mv -f _s$*.o $*.lo
 .c.txt:
 	$(CPP) $(INCLUDES) $(CPPFLAGS) $< >$*.txt
 .c:
-	$(C_COMPILE) -o $* $< $(LDFLAGS) $(LIBS)
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              $<" ; \
+	else \
+	  echo $(C_COMPILE) -o $* $< $(LDFLAGS) $(LIBS) ; \
+	fi
+	@$(C_COMPILE) -o $* $< $(LDFLAGS) $(LIBS)
 .c.man:
 	$(DOCTEXT) -man -mpath ../../../man/man3 -ext 3 -heading MPI \
 		-quotefmt ${master_top_srcdir}/maint/docnotes $<
@@ -67,13 +84,14 @@ INCLUDES = -I../../include -I${top_srcdir}/src/include
 
 # --------------------------------------------------------------------------
 ${srcdir}/Makefile.in: ${srcdir}/Makefile.sm
-	( cd ${srcdir} && /sandbox/balaji/trunk/maint/mpich2-1.0.7/maint/simplemake \
+	( cd ${srcdir} && ${master_top_srcdir}/maint/simplemake \
 	-rootdir=../../../ \
 	-configdir=. \
-	-common=/sandbox/balaji/trunk/maint/mpich2-1.0.7/maint/makedefs \
-	-docnamedefs=\$${master_top_srcdir}/maint/docnotes \
+	-common=${master_top_srcdir}/maint/makedefs \
+	-docnamedefs=${master_top_srcdir}/maint/docnotes \
 	"-autoconf=-I ROOTDIR/confdb" \
-	-libdir=\$${MPILIBNAME}=ROOTDIR/lib \
+	-libdir='$${MPILIBNAME}=ROOTDIR/lib' \
+	-smroot=${master_top_srcdir}/maint \
 	-distcleanfiles="Makefile" \
 	-smvar_doc_attop=0 \
 		Makefile.sm )
@@ -120,7 +138,12 @@ all-redirect: .libstamp0 ../../../lib/lib${MPILIBNAME}.a
 	file_create_errhandler.o file_get_errhandler.o file_set_errhandler.o \
 	file_call_errhandler.o win_create_errhandler.o win_call_errhandler.o \
 	win_get_errhandler.o win_set_errhandler.o errutil.o dynerrutil.o 
-	${AR} cr ../../../lib/lib${MPILIBNAME}.a $?
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  AR cr ../../../lib/lib${MPILIBNAME}.a $?" ; \
+	else \
+	  echo ${AR} cr ../../../lib/lib${MPILIBNAME}.a $? ; \
+	fi
+	@${AR} cr ../../../lib/lib${MPILIBNAME}.a $?
 	${RANLIB} ../../../lib/lib${MPILIBNAME}.a
 	date > .libstamp0
 .libstamp1 ../../../lib/lib${MPILIBNAME}.la: add_error_code.lo \
@@ -132,7 +155,12 @@ all-redirect: .libstamp0 ../../../lib/lib${MPILIBNAME}.a
 	file_set_errhandler.lo file_call_errhandler.lo \
 	win_create_errhandler.lo win_call_errhandler.lo win_get_errhandler.lo \
 	win_set_errhandler.lo errutil.lo dynerrutil.lo 
-	${AR} cr ../../../lib/lib${MPILIBNAME}.la $?
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  AR cr ../../../lib/lib${MPILIBNAME}.la $?" ; \
+	else \
+	  echo ${AR} cr ../../../lib/lib${MPILIBNAME}.la $? ; \
+	fi
+	@${AR} cr ../../../lib/lib${MPILIBNAME}.la $?
 	date > .libstamp1
 
 # --------------------------------------------------------------------------
@@ -144,8 +172,18 @@ all-redirect: .libstamp0 ../../../lib/lib${MPILIBNAME}.a
 	_file_set_errhandler.o _file_call_errhandler.o \
 	_win_create_errhandler.o _win_call_errhandler.o _win_get_errhandler.o \
 	_win_set_errhandler.o 
-	${AR} cr ../../../lib/lib${PMPILIBNAME}.a $?
-	${RANLIB} ../../../lib/lib${PMPILIBNAME}.a
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  AR cr ../../../lib/lib${PMPILIBNAME}.a $?" ; \
+	else \
+	  echo ${AR} cr ../../../lib/lib${PMPILIBNAME}.a $? ; \
+	fi
+	@${AR} cr ../../../lib/lib${PMPILIBNAME}.a $?
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  RANLIB          lib${PMPILIBNAME}.a" ; \
+	else \
+	  echo ${RANLIB} ../../../lib/lib${PMPILIBNAME}.a ; \
+	fi
+	@${RANLIB} ../../../lib/lib${PMPILIBNAME}.a
 	date > .libstamp2
 .libstamp3: _add_error_code.lo _add_error_class.lo _add_error_string.lo \
 	_comm_call_errhandler.lo _comm_create_errhandler.lo \
@@ -155,90 +193,200 @@ all-redirect: .libstamp0 ../../../lib/lib${MPILIBNAME}.a
 	_file_get_errhandler.lo _file_set_errhandler.lo \
 	_file_call_errhandler.lo _win_create_errhandler.lo \
 	_win_call_errhandler.lo _win_get_errhandler.lo _win_set_errhandler.lo 
-	${AR} cr ../../../lib/lib${PMPILIBNAME}.la $?
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  AR cr ../../../lib/lib${PMPILIBNAME}.la $?" ; \
+	else \
+	  echo ${AR} cr ../../../lib/lib${PMPILIBNAME}.la $?; \
+	fi
+	@${AR} cr ../../../lib/lib${PMPILIBNAME}.la $?
 	date > .libstamp3
 _add_error_code.o: add_error_code.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/add_error_code.c -o _add_error_code.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/add_error_code.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/add_error_code.c -o _add_error_code.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/add_error_code.c -o _add_error_code.o
 _add_error_code.lo: add_error_code.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/add_error_code.c -o _add_error_code.lo
 _add_error_class.o: add_error_class.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/add_error_class.c -o _add_error_class.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/add_error_class.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/add_error_class.c -o _add_error_class.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/add_error_class.c -o _add_error_class.o
 _add_error_class.lo: add_error_class.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/add_error_class.c -o _add_error_class.lo
 _add_error_string.o: add_error_string.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/add_error_string.c -o _add_error_string.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/add_error_string.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/add_error_string.c -o _add_error_string.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/add_error_string.c -o _add_error_string.o
 _add_error_string.lo: add_error_string.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/add_error_string.c -o _add_error_string.lo
 _comm_call_errhandler.o: comm_call_errhandler.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/comm_call_errhandler.c -o _comm_call_errhandler.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/comm_call_errhandler.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/comm_call_errhandler.c -o _comm_call_errhandler.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/comm_call_errhandler.c -o _comm_call_errhandler.o
 _comm_call_errhandler.lo: comm_call_errhandler.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/comm_call_errhandler.c -o _comm_call_errhandler.lo
 _comm_create_errhandler.o: comm_create_errhandler.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/comm_create_errhandler.c -o _comm_create_errhandler.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/comm_create_errhandler.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/comm_create_errhandler.c -o _comm_create_errhandler.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/comm_create_errhandler.c -o _comm_create_errhandler.o
 _comm_create_errhandler.lo: comm_create_errhandler.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/comm_create_errhandler.c -o _comm_create_errhandler.lo
 _comm_get_errhandler.o: comm_get_errhandler.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/comm_get_errhandler.c -o _comm_get_errhandler.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/comm_get_errhandler.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/comm_get_errhandler.c -o _comm_get_errhandler.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/comm_get_errhandler.c -o _comm_get_errhandler.o
 _comm_get_errhandler.lo: comm_get_errhandler.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/comm_get_errhandler.c -o _comm_get_errhandler.lo
 _comm_set_errhandler.o: comm_set_errhandler.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/comm_set_errhandler.c -o _comm_set_errhandler.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/comm_set_errhandler.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/comm_set_errhandler.c -o _comm_set_errhandler.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/comm_set_errhandler.c -o _comm_set_errhandler.o
 _comm_set_errhandler.lo: comm_set_errhandler.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/comm_set_errhandler.c -o _comm_set_errhandler.lo
 _errhandler_create.o: errhandler_create.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/errhandler_create.c -o _errhandler_create.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/errhandler_create.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/errhandler_create.c -o _errhandler_create.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/errhandler_create.c -o _errhandler_create.o
 _errhandler_create.lo: errhandler_create.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/errhandler_create.c -o _errhandler_create.lo
 _errhandler_free.o: errhandler_free.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/errhandler_free.c -o _errhandler_free.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/errhandler_free.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/errhandler_free.c -o _errhandler_free.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/errhandler_free.c -o _errhandler_free.o
 _errhandler_free.lo: errhandler_free.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/errhandler_free.c -o _errhandler_free.lo
 _errhandler_get.o: errhandler_get.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/errhandler_get.c -o _errhandler_get.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/errhandler_get.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/errhandler_get.c -o _errhandler_get.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/errhandler_get.c -o _errhandler_get.o
 _errhandler_get.lo: errhandler_get.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/errhandler_get.c -o _errhandler_get.lo
 _errhandler_set.o: errhandler_set.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/errhandler_set.c -o _errhandler_set.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/errhandler_set.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/errhandler_set.c -o _errhandler_set.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/errhandler_set.c -o _errhandler_set.o
 _errhandler_set.lo: errhandler_set.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/errhandler_set.c -o _errhandler_set.lo
 _error_class.o: error_class.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/error_class.c -o _error_class.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/error_class.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/error_class.c -o _error_class.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/error_class.c -o _error_class.o
 _error_class.lo: error_class.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/error_class.c -o _error_class.lo
 _error_string.o: error_string.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/error_string.c -o _error_string.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/error_string.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/error_string.c -o _error_string.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/error_string.c -o _error_string.o
 _error_string.lo: error_string.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/error_string.c -o _error_string.lo
 _file_create_errhandler.o: file_create_errhandler.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/file_create_errhandler.c -o _file_create_errhandler.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/file_create_errhandler.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/file_create_errhandler.c -o _file_create_errhandler.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/file_create_errhandler.c -o _file_create_errhandler.o
 _file_create_errhandler.lo: file_create_errhandler.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/file_create_errhandler.c -o _file_create_errhandler.lo
 _file_get_errhandler.o: file_get_errhandler.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/file_get_errhandler.c -o _file_get_errhandler.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/file_get_errhandler.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/file_get_errhandler.c -o _file_get_errhandler.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/file_get_errhandler.c -o _file_get_errhandler.o
 _file_get_errhandler.lo: file_get_errhandler.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/file_get_errhandler.c -o _file_get_errhandler.lo
 _file_set_errhandler.o: file_set_errhandler.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/file_set_errhandler.c -o _file_set_errhandler.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/file_set_errhandler.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/file_set_errhandler.c -o _file_set_errhandler.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/file_set_errhandler.c -o _file_set_errhandler.o
 _file_set_errhandler.lo: file_set_errhandler.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/file_set_errhandler.c -o _file_set_errhandler.lo
 _file_call_errhandler.o: file_call_errhandler.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/file_call_errhandler.c -o _file_call_errhandler.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/file_call_errhandler.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/file_call_errhandler.c -o _file_call_errhandler.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/file_call_errhandler.c -o _file_call_errhandler.o
 _file_call_errhandler.lo: file_call_errhandler.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/file_call_errhandler.c -o _file_call_errhandler.lo
 _win_create_errhandler.o: win_create_errhandler.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/win_create_errhandler.c -o _win_create_errhandler.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/win_create_errhandler.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/win_create_errhandler.c -o _win_create_errhandler.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/win_create_errhandler.c -o _win_create_errhandler.o
 _win_create_errhandler.lo: win_create_errhandler.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/win_create_errhandler.c -o _win_create_errhandler.lo
 _win_call_errhandler.o: win_call_errhandler.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/win_call_errhandler.c -o _win_call_errhandler.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/win_call_errhandler.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/win_call_errhandler.c -o _win_call_errhandler.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/win_call_errhandler.c -o _win_call_errhandler.o
 _win_call_errhandler.lo: win_call_errhandler.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/win_call_errhandler.c -o _win_call_errhandler.lo
 _win_get_errhandler.o: win_get_errhandler.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/win_get_errhandler.c -o _win_get_errhandler.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/win_get_errhandler.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/win_get_errhandler.c -o _win_get_errhandler.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/win_get_errhandler.c -o _win_get_errhandler.o
 _win_get_errhandler.lo: win_get_errhandler.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/win_get_errhandler.c -o _win_get_errhandler.lo
 _win_set_errhandler.o: win_set_errhandler.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/win_set_errhandler.c -o _win_set_errhandler.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/win_set_errhandler.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/win_set_errhandler.c -o _win_set_errhandler.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/win_set_errhandler.c -o _win_set_errhandler.o
 _win_set_errhandler.lo: win_set_errhandler.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/win_set_errhandler.c -o _win_set_errhandler.lo
 # --------------------------------------------------------------------------
diff --git a/mpich2/src/mpi/init/Makefile.in b/mpich2/src/mpi/init/Makefile.in
--- a/mpich2/src/mpi/init/Makefile.in
+++ b/mpich2/src/mpi/init/Makefile.in
@@ -6,6 +6,7 @@
 all: all-redirect
 
 SHELL           = @SHELL@
+VERBOSE         = 1
 AR              = @AR@
 RANLIB          = @RANLIB@
 master_top_srcdir  = @master_top_srcdir@
@@ -37,14 +38,30 @@ INCLUDES = -I../../include -I${top_srcdir}/src/include -I${top_srcdir}/src/mpi/d
 .SUFFIXES:
 .SUFFIXES: .o .lo .c .man .html .latex .txt 
 .c.o:
-	$(C_COMPILE) -c $<
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              $<" ; \
+	else \
+	  echo $(C_COMPILE) -c $< ; \
+	fi
+	@$(C_COMPILE) -c $<
 .c.lo:
-	$(C_COMPILE_SHL) -c $< -o _s$*.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              $<" ; \
+	else \
+	  echo $(C_COMPILE_SHL) -c $< -o _s$*.o ; \
+	echo mv -f _s$*.o $*.lo ; \
+	fi
+	@$(C_COMPILE_SHL) -c $< -o _s$*.o
 	@mv -f _s$*.o $*.lo
 .c.txt:
 	$(CPP) $(INCLUDES) $(CPPFLAGS) $< >$*.txt
 .c:
-	$(C_COMPILE) -o $* $< $(LDFLAGS) $(LIBS)
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              $<" ; \
+	else \
+	  echo $(C_COMPILE) -o $* $< $(LDFLAGS) $(LIBS) ; \
+	fi
+	@$(C_COMPILE) -o $* $< $(LDFLAGS) $(LIBS)
 .c.man:
 	$(DOCTEXT) -man -mpath ../../../man/man3 -ext 3 -heading MPI \
 		-quotefmt ${master_top_srcdir}/maint/docnotes $<
@@ -57,13 +74,14 @@ INCLUDES = -I../../include -I${top_srcdir}/src/include -I${top_srcdir}/src/mpi/d
 
 # --------------------------------------------------------------------------
 ${srcdir}/Makefile.in: ${srcdir}/Makefile.sm
-	( cd ${srcdir} && /sandbox/balaji/trunk/maint/mpich2-1.0.7/maint/simplemake \
+	( cd ${srcdir} && ${master_top_srcdir}/maint/simplemake \
 	-rootdir=../../../ \
 	-configdir=. \
-	-common=/sandbox/balaji/trunk/maint/mpich2-1.0.7/maint/makedefs \
-	-docnamedefs=\$${master_top_srcdir}/maint/docnotes \
+	-common=${master_top_srcdir}/maint/makedefs \
+	-docnamedefs=${master_top_srcdir}/maint/docnotes \
 	"-autoconf=-I ROOTDIR/confdb" \
-	-libdir=\$${MPILIBNAME}=ROOTDIR/lib \
+	-libdir='$${MPILIBNAME}=ROOTDIR/lib' \
+	-smroot=${master_top_srcdir}/maint \
 	-distcleanfiles="Makefile" \
 	-smvar_doc_attop=0 \
 		Makefile.sm )
@@ -104,55 +122,120 @@ all-redirect: .libstamp0 ../../../lib/lib${MPILIBNAME}.a
 
 .libstamp0 ../../../lib/lib${MPILIBNAME}.a: abort.o init.o initialized.o \
 	initthread.o ismain.o finalize.o finalized.o querythread.o initinfo.o 
-	${AR} cr ../../../lib/lib${MPILIBNAME}.a $?
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  AR cr ../../../lib/lib${MPILIBNAME}.a $?" ; \
+	else \
+	  echo ${AR} cr ../../../lib/lib${MPILIBNAME}.a $? ; \
+	fi
+	@${AR} cr ../../../lib/lib${MPILIBNAME}.a $?
 	${RANLIB} ../../../lib/lib${MPILIBNAME}.a
 	date > .libstamp0
 .libstamp1 ../../../lib/lib${MPILIBNAME}.la: abort.lo init.lo initialized.lo \
 	initthread.lo ismain.lo finalize.lo finalized.lo querythread.lo \
 	initinfo.lo 
-	${AR} cr ../../../lib/lib${MPILIBNAME}.la $?
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  AR cr ../../../lib/lib${MPILIBNAME}.la $?" ; \
+	else \
+	  echo ${AR} cr ../../../lib/lib${MPILIBNAME}.la $? ; \
+	fi
+	@${AR} cr ../../../lib/lib${MPILIBNAME}.la $?
 	date > .libstamp1
 
 # --------------------------------------------------------------------------
 .libstamp2: _abort.o _init.o _initialized.o _initthread.o _ismain.o _finalize.o \
 	_finalized.o _querythread.o 
-	${AR} cr ../../../lib/lib${PMPILIBNAME}.a $?
-	${RANLIB} ../../../lib/lib${PMPILIBNAME}.a
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  AR cr ../../../lib/lib${PMPILIBNAME}.a $?" ; \
+	else \
+	  echo ${AR} cr ../../../lib/lib${PMPILIBNAME}.a $? ; \
+	fi
+	@${AR} cr ../../../lib/lib${PMPILIBNAME}.a $?
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  RANLIB          lib${PMPILIBNAME}.a" ; \
+	else \
+	  echo ${RANLIB} ../../../lib/lib${PMPILIBNAME}.a ; \
+	fi
+	@${RANLIB} ../../../lib/lib${PMPILIBNAME}.a
 	date > .libstamp2
 .libstamp3: _abort.lo _init.lo _initialized.lo _initthread.lo _ismain.lo _finalize.lo \
 	_finalized.lo _querythread.lo 
-	${AR} cr ../../../lib/lib${PMPILIBNAME}.la $?
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  AR cr ../../../lib/lib${PMPILIBNAME}.la $?" ; \
+	else \
+	  echo ${AR} cr ../../../lib/lib${PMPILIBNAME}.la $?; \
+	fi
+	@${AR} cr ../../../lib/lib${PMPILIBNAME}.la $?
 	date > .libstamp3
 _abort.o: abort.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/abort.c -o _abort.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/abort.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/abort.c -o _abort.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/abort.c -o _abort.o
 _abort.lo: abort.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/abort.c -o _abort.lo
 _init.o: init.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/init.c -o _init.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/init.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/init.c -o _init.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/init.c -o _init.o
 _init.lo: init.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/init.c -o _init.lo
 _initialized.o: initialized.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/initialized.c -o _initialized.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/initialized.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/initialized.c -o _initialized.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/initialized.c -o _initialized.o
 _initialized.lo: initialized.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/initialized.c -o _initialized.lo
 _initthread.o: initthread.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/initthread.c -o _initthread.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/initthread.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/initthread.c -o _initthread.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/initthread.c -o _initthread.o
 _initthread.lo: initthread.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/initthread.c -o _initthread.lo
 _ismain.o: ismain.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/ismain.c -o _ismain.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/ismain.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/ismain.c -o _ismain.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/ismain.c -o _ismain.o
 _ismain.lo: ismain.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/ismain.c -o _ismain.lo
 _finalize.o: finalize.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/finalize.c -o _finalize.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/finalize.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/finalize.c -o _finalize.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/finalize.c -o _finalize.o
 _finalize.lo: finalize.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/finalize.c -o _finalize.lo
 _finalized.o: finalized.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/finalized.c -o _finalized.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/finalized.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/finalized.c -o _finalized.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/finalized.c -o _finalized.o
 _finalized.lo: finalized.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/finalized.c -o _finalized.lo
 _querythread.o: querythread.c
-	$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/querythread.c -o _querythread.o
+	@if [ "x$(VERBOSE)" != "x1" ] ; then \
+	  echo "  CC              ${srcdir}/querythread.c" ; \
+	else \
+	  echo $(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/querythread.c -o _querythread.o ; \
+	fi
+	@$(C_COMPILE) -c @PROFILE_DEF_MPI@ $(srcdir)/querythread.c -o _querythread.o
 _querythread.lo: querythread.c
 	$(C_COMPILE_SHL) -c @PROFILE_DEF_MPI@ $(srcdir)/querythread.c -o _querythread.lo
 # --------------------------------------------------------------------------
