Vendor version 1.3.2

diff --git a/mpich2/src/binding/f90/buildiface b/mpich2/src/binding/f90/buildiface
--- a/mpich2/src/binding/f90/buildiface
+++ b/mpich2/src/binding/f90/buildiface
@@ -280,7 +280,7 @@ close (MPIFD);
 # This is the file for the routines that have no "choice" arguments.
 # An example of a choice argument is a "void *buf" input argument to 
 # MPI_Send, which allows any buffer address, both numeric and character.
-open ( MPIBASEFD, ">${outfile_prefix}_base.f90.new" ) || die "Could not open ${outfile_prefix}_base.f90.new\n";
+open ( MPIBASEFD, ">${outfile_prefix}_base.f90.in.new" ) || die "Could not open ${outfile_prefix}_base.f90.in.new\n";
 print MPIBASEFD "!  (C) 2008 by Argonne National Laboratory.
 !      See COPYRIGHT in top-level directory.       
        MODULE ${ucoutfile_prefix}_BASE
@@ -345,19 +345,19 @@ if ($is_MPI) {
         END SUBROUTINE MPI_INIT_THREAD
 
         FUNCTION MPI_WTIME()
-            DOUBLE PRECISION MPI_WTIME
+            \@WTIME_DOUBLE_TYPE\@ MPI_WTIME
         END FUNCTION MPI_WTIME
 !
         FUNCTION MPI_WTICK()
-            DOUBLE PRECISION MPI_WTICK
+            \@WTIME_DOUBLE_TYPE\@ MPI_WTICK
         END FUNCTION MPI_WTICK
 
         FUNCTION PMPI_WTIME()
-            DOUBLE PRECISION PMPI_WTIME
+            \@WTIME_DOUBLE_TYPE\@ PMPI_WTIME
         END FUNCTION PMPI_WTIME
 !
         FUNCTION PMPI_WTICK()
-            DOUBLE PRECISION PMPI_WTICK
+            \@WTIME_DOUBLE_TYPE\@ PMPI_WTICK
         END FUNCTION PMPI_WTICK
 
         SUBROUTINE MPI_NULL_DELETE_FN(a,b,c,d,e)
@@ -508,7 +508,7 @@ if ($buildScalarVector) {
 
 print MPIBASEFD "       END MODULE ${ucoutfile_prefix}_BASE\n";
 close MPIBASEFD;
-&ReplaceIfDifferent( "${outfile_prefix}_base.f90", "${outfile_prefix}_base.f90.new" );
+&ReplaceIfDifferent( "${outfile_prefix}_base.f90.in", "${outfile_prefix}_base.f90.in.new" );
 
 open ( MPIFD, ">${outfile_prefix}_constants.f90.new" ) || die "Cannot open ${outfile_prefix}_constants.f90.new\n";
 print MPIFD "!  (C) 2008 by Argonne National Laboratory.
@@ -653,19 +653,19 @@ print MAKEFD "smvar_do_dependencies = ignore\n";
 #print MAKEFD "smvar_do_sharedlibs   = 0\n";
 print MAKEFD "smvar_makefile_configdir = ../../..\n";
 #print MAKEFD "smvar_debug=1\n";
-print MAKEFD "MOD              = \@F90MODEXT\@\n";
+print MAKEFD "MOD              = \@FCMODEXT\@\n";
 print MAKEFD "MPIMOD           = \@MPIMODNAME\@\n";
 print MAKEFD "MPICONSTMOD      = \@MPICONSTMODNAME\@\n";
 print MAKEFD "MPISIZEOFMOD     = \@MPISIZEOFMODNAME\@\n";
 print MAKEFD "MPIBASEMOD       = \@MPIBASEMODNAME\@\n";
-print MAKEFD "F90INCFLAG       = \@F90INCFLAG\@\n";
-print MAKEFD "F90EXT           = \@F90EXT\@\n";
-print MAKEFD "F90_COMPILE_MODS = \$(F90_COMPILE)\n";
+print MAKEFD "FCINCFLAG        = \@FCINCFLAG\@\n";
+print MAKEFD "FCEXT            = \@FCEXT\@\n";
+print MAKEFD "FC_COMPILE_MODS  = \$(FC_COMPILE)\n";
 print MAKEFD 
 "# We need to tell some compilers (e.g., Solaris f90) to look in the current 
 # directory when the source file is not in the working directory (i.e.,
 # in a VPATH build)
-F90INCLUDES = \@F90INCFLAG\@.
+FCINCLUDES = \@FCINCFLAG\@.
 
 ";
 
@@ -687,9 +687,9 @@ lib\${MPILIBNAME}f90_a_SOURCES = mpi.o mpi_constants.o mpi_sizeofs.o ${outfile_p
 print MAKEFD "all-preamble: \$(MPIMOD).\$(MOD)\n";
 
 print MAKEFD "\
-# The copy line in this step makes the F90 modules available to
+# The copy line in this step makes the Fortran90 modules available to
 # the mpif90 script before an install takes place
-# The if handles the Intel F90 compiler, which has an unusual interface
+# The if handles the Intel Fortran90 compiler, which has an unusual interface
 # (The mpimod.pcl file should contain only a local mpimod.pc name; if
 # it contains a file name in another directory and that file does not 
 # exist, the compiler may refuse to compile the file)
@@ -710,9 +710,9 @@ print MAKEFD "\
 
 #print MAKEFD "\tcp mpi.\$(MOD) mpi_constants.\$(MOD) mpi_base.\$(MOD) mpi_sizeofs.\$(MOD) ../../../src/include\n";
 #
-# Some versions of the Intel f90 compiler require special files that 
+# Some versions of the Intel Fortran90 compiler require special files that 
 # describe which modules to load.
-#print MAKEFD "\t\@if [ -n \"\@F90_WORK_FILES_ARG\@\" ] ; then \\\
+#print MAKEFD "\t\@if [ -n \"\@FC_WORK_FILES_ARG\@\" ] ; then \\\
 #\t    cp work.pc ../../../src/include/mpimod.pc ; \\\
 #\t    echo \"mpimod.pc\" > mpimod.pcl ; \\\
 #\t    echo \"\${includedir}/mpimod.pc\" >> mpimod.pcl ;\\\
@@ -725,8 +725,8 @@ print MAKEFD "\$(MPICONSTMOD).\$(MOD): \$(srcdir)/mpi_constants.f90 mpifnoext.h\
 print MAKEFD "\$(MPISIZEOFMOD).\$(MOD): mpi_sizeofs.f90 mpifnoext.h\n";
 &createModSteps( "mpi_sizeofs.f90" );
 
-print MAKEFD "\$(MPIBASEMOD).\$(MOD): \$(srcdir)/${outfile_prefix}_base.f90\n";
-&createModSteps( '$(srcdir)/' . $outfile_prefix . '_base.f90' );
+print MAKEFD "\$(MPIBASEMOD).\$(MOD): ${outfile_prefix}_base.f90\n";
+&createModSteps( $outfile_prefix . '_base.f90' );
 
 print MAKEFD "\
 # We need a free-format version of mpif.h with no external commands,
@@ -756,6 +756,7 @@ all-postamble:
 print MAKEFD "clean-local:\n";
 print MAKEFD "\trm -f *.\$(MOD)\n";
 print MAKEFD "\trm -f mpimod.pcl mpimod.pc\n";
+print MAKEFD "\trm -f lib\${MPILIBNAME}f90.a\n";
 
 print MAKEFD "maint-clean:\
 \trm -f \${mpi_sources} fproto.h\n";
@@ -784,7 +785,7 @@ doc_LATEX_SOURCES = \${doc_sources}
 # selected by configure from a list of possible choices, with an 
 # enable switch used to bypass the checks.  In addition, we need a way to 
 # dynamically create subsets, given a list of routines and types/dimensions 
-# to include.  This allows users to build precisely tailored F90 modules.
+# to include.  This allows users to build precisely tailored Fortran90 modules.
 # ----------------------------------------------------------------------------
 
 # Since configure copies mpif90 to the bin dir, we need to remove it
@@ -840,26 +841,26 @@ sub print_endline {
 sub createModSteps {
     my ($srcFile) = @_;
     
-    # Get a version of the source file with $(F90EXT) instead of .f90
+    # Get a version of the source file with $(FCEXT) instead of .f90
     # as the extension
     my $srcFileWithExt = $srcFile;
-    $srcFileWithExt =~ s/\.f90$/\.\$(F90EXT)/;
+    $srcFileWithExt =~ s/\.f90$/\.\$(FCEXT)/;
 
 print MAKEFD 
-"\t\@if [ -n \"\@F90_WORK_FILES_ARG\@\" ] ; then \\
+"\t\@if [ -n \"\@FC_WORK_FILES_ARG\@\" ] ; then \\
 	    rm -f mpimod.pc mpimod.pcl ; \\
 	    echo \"mpimod.pc\" > mpimod.pcl ; \\
-	    echo \$(F90_COMPILE_MODS) \@F90_WORK_FILES_ARG\@ -c $srcFile ; \\
-	    \$(F90_COMPILE_MODS) \@F90_WORK_FILES_ARG\@ -c $srcFile ; \\
+	    echo \$(FC_COMPILE_MODS) \@FC_WORK_FILES_ARG\@ -c $srcFile ; \\
+	    \$(FC_COMPILE_MODS) \@FC_WORK_FILES_ARG\@ -c $srcFile ; \\
 	    cp mpimod.pc ../../../src/include/mpimod.pc ; \\
 	    cp mpimod.pcl ../../../src/include/mpimod.pcl ; \\
 	else \\
-	    if [ \"\$(F90EXT)\" != \"f90\" ] ; then \\
+	    if [ \"\$(FCEXT)\" != \"f90\" ] ; then \\
 	        ln -f -s $srcFile $srcFileWithExt ; \\
 	    fi ; \\
-	    echo \$(F90_COMPILE_MODS) -c $srcFileWithExt ; \\
-	    \$(F90_COMPILE_MODS) -c $srcFileWithExt ; \\
-	    if [ \"\$(F90EXT)\" != \"f90\" ] ; then \\
+	    echo \$(FC_COMPILE_MODS) -c $srcFileWithExt ; \\
+	    \$(FC_COMPILE_MODS) -c $srcFileWithExt ; \\
+	    if [ \"\$(FCEXT)\" != \"f90\" ] ; then \\
 	        rm -f $srcFileWithExt ; \\
 	    fi ; \\
 	fi
@@ -996,6 +997,9 @@ sub ReplaceIfDifferent {
 	# with the new one
 	if (-s $oldfilename) {
 	    print STDERR "Replacing $oldfilename\n";
+	    # If debugging and there is a difference, show that difference
+	    if ($gDebug) { system "diff $newfilename $oldfilename"; }
+
 	    unlink $oldfilename;
 	}
 	else {
diff --git a/mpich2/src/mpid/ch3/channels/dllchan/configure b/mpich2/src/mpid/ch3/channels/dllchan/configure
--- a/mpich2/src/mpid/ch3/channels/dllchan/configure
+++ b/mpich2/src/mpid/ch3/channels/dllchan/configure
@@ -654,6 +654,7 @@ AR_FLAGS
 AR
 channel_name
 device_name
+ABIVERSION
 EGREP
 GREP
 CPP
@@ -1927,6 +1928,8 @@ save_libs=$LIBS
 LIBS=
 
 
+# This is needed for Mac OSX 10.5
+rm -rf conftest.dSYM
 rm -f conftest*
 date >conftest$$
 # If creating a file in the current directory does not show up in the srcdir
@@ -1973,6 +1976,8 @@ $as_echo "$as_me: error: You cannot do a VPATH build if the source directory has
         fi
     fi
 fi
+# This is needed for Mac OSX 10.5
+rm -rf conftest.dSYM
 rm -f conftest*
 
 
@@ -2145,7 +2150,6 @@ fi
 
 
 
-
 { $as_echo "$as_me:$LINENO: checking for virtual path format" >&5
 $as_echo_n "checking for virtual path format... " >&6; }
 if test "${pac_cv_prog_make_vpath+set}" = set; then
@@ -2196,7 +2200,6 @@ if test "$pac_cv_prog_make_vpath" = "VPATH" ; then
 elif test "$pac_cv_prog_make_vpath" = ".PATH" ; then
     VPATH='.PATH: . ${srcdir}'
 fi
-
 
 
 
@@ -3991,6 +3994,21 @@ _ACEOF
 # AR_FLAGS provides a way to potentially improve build performance on Mac OSX
 if test -z "$AR_FLAGS" ; then AR_FLAGS=cr ; fi
 
+# ABIVERSION is needed when a separate sock dll library is built (e.g., for
+# dllchan)
+if test "X$ABIVERSION" = "X" ; then
+   if test "X$libmpich_so_version" != X ; then
+      ABIVERSION="$libmpich_so_version"
+   else
+      # Note that an install of a sock-dll will fail if the ABI version is not
+      # available
+      { $as_echo "$as_me:$LINENO: WARNING: Unable to set the ABIVERSION" >&5
+$as_echo "$as_me: WARNING: Unable to set the ABIVERSION" >&2;}
+   fi
+fi
+
+
+
 
 
 
@@ -4051,6 +4069,8 @@ fi
 if test -z "$channel_args" ; then
      channel_args=sock
 fi
+
+export ABIVERSION
 
 channel_args=`echo $channel_args | sed -e 's/,/ /g'`
 builddir=`(cd .. && pwd)`
diff --git a/mpich2/src/mpid/ch3/channels/sock/builddll b/mpich2/src/mpid/ch3/channels/sock/builddll
--- a/mpich2/src/mpid/ch3/channels/sock/builddll
+++ b/mpich2/src/mpid/ch3/channels/sock/builddll
@@ -1,6 +1,7 @@
 #! /bin/sh
 #
 set -x
+printenv
 # This script builds a stand-alone DLL for the socket channel.
 # It makes use of the configure scripts in the necessary components
 #
@@ -36,6 +37,12 @@ for arg do
 done
 BUILD_DLLS=yes
 export BUILD_DLLS
+#
+# We must have a valid ABIVERSION
+if [ "X$ABIVERSION" = "X" ] ; then
+    echo "No ABIVERSION available - required to build sock DLL"
+    exit 1
+fi
 #
 # Determine shared library type (only a few supported)
 osname=`uname -s`
diff --git a/mpich2/src/mpid/ch3/channels/sock/configure b/mpich2/src/mpid/ch3/channels/sock/configure
--- a/mpich2/src/mpid/ch3/channels/sock/configure
+++ b/mpich2/src/mpid/ch3/channels/sock/configure
@@ -637,7 +637,6 @@ ac_includes_default="\
 
 ac_subst_vars='LTLIBOBJS
 LIBOBJS
-ABIVERSION
 ETAGSADD
 ETAGS
 MAKE_DEPEND_C
@@ -675,6 +674,7 @@ RANLIB
 INSTALL_DATA
 INSTALL_SCRIPT
 INSTALL_PROGRAM
+ABIVERSION
 target_alias
 host_alias
 build_alias
@@ -1930,7 +1930,23 @@ ac_config_headers="$ac_config_headers include/mpidi_ch3i_sock_conf.h"
 
 echo "RUNNING CONFIGURE FOR THE SOCK CHANNEL"
 
+# ABIVERSION is needed when a separate sock dll library is built (e.g., for
+# dllchan)
+if test "X$ABIVERSION" = "X" ; then
+   if test "X$libmpich_so_version" != X ; then
+      ABIVERSION="$libmpich_so_version"
+   else
+      # Note that an install of a sock-dll will fail if the ABI version is not
+      # available
+      { $as_echo "$as_me:$LINENO: WARNING: Unable to set the ABIVERSION" >&5
+$as_echo "$as_me: WARNING: Unable to set the ABIVERSION" >&2;}
+   fi
+fi
 
+
+
+# This is needed for Mac OSX 10.5
+rm -rf conftest.dSYM
 rm -f conftest*
 date >conftest$$
 # If creating a file in the current directory does not show up in the srcdir
@@ -1977,6 +1993,8 @@ $as_echo "$as_me: error: You cannot do a VPATH build if the source directory has
         fi
     fi
 fi
+# This is needed for Mac OSX 10.5
+rm -rf conftest.dSYM
 rm -f conftest*
 
 
@@ -2086,6 +2104,15 @@ if test -z "$INSTALL" ; then
     { $as_echo "$as_me:$LINENO: result: No install program available" >&5
 $as_echo "No install program available" >&6; }
 else
+    # first make any "confdb/install-sh -c" into an absolute path
+    # this is a hack, but it's still much cleaner than anything else I could
+    # come up with (see tt#1007) [goodell@]
+    case "$INSTALL" in
+  /*) : ;;
+  *install-sh*) INSTALL="$master_top_srcdir/$INSTALL" ;;
+esac
+
+
     # Check that this install really works
     rm -f conftest
     echo "Test file" > conftest
@@ -3394,7 +3421,6 @@ fi
 
 
 
-
 { $as_echo "$as_me:$LINENO: checking for virtual path format" >&5
 $as_echo_n "checking for virtual path format... " >&6; }
 if test "${pac_cv_prog_make_vpath+set}" = set; then
@@ -3445,7 +3471,6 @@ if test "$pac_cv_prog_make_vpath" = "VPATH" ; then
 elif test "$pac_cv_prog_make_vpath" = ".PATH" ; then
     VPATH='.PATH: . ${srcdir}'
 fi
-
 
 
 
@@ -4593,10 +4618,6 @@ if test -n "$CONF_BASE_CACHEFILE" -a -s "$CONF_BASE_CACHEFILE" ; then
 	mv $CONF_BASE_CACHEFILE.new $CONF_BASE_CACHEFILE
     fi
 fi
-
-
-# define the ABI version of the channel ABI that we are using.
-ABIVERSION=1:1
 
 
 ac_config_commands="$ac_config_commands default-1"
